from enum import Enum

class Packet(Enum):
    KEEPALIVE = 0
    CREATE_LOBBY = 1
    LOBBY_STATE = 2
    START_GAME = 3
    REQUEST_PROMPT = 4
    DRAWING_PROMPT = 5
    DRAWING_SUBMISSION = 6
    CAPTION_PROMPT = 7
    CAPTION_SUBMISSION = 8
    CLOSE_LOBBY = 9
    DISCONNECT = 10
    SET_NAME = 11
