CLIENT_TYPE_TRANSMITTER = 0x01
CLIENT_TYPE_RECEIVER = 0x02

KEEPALIVE = 0
CREATE_LOBBY = 1
LOBBY_STATE = 2
START_GAME = 3
REQUEST_PROMPT = 4
DRAWING_PROMPT = 5
DRAWING_SUBMISSION = 6
CAPTION_PROMPT = 7
CAPTION_SUBMISSION = 8
CLOSE_LOBBY = 9
DISCONNECT = 10
SET_LITTLE_ENDIAN = 11
SET_BIG_ENDIAN = 12
SET_NAME = 13
